server.port: 8081

spring:
  application.name: home-budget-tracker

  datasource:
    url: jdbc:postgresql://localhost:15432/budgettracker
    username: budgettracker
    password: budgettracker
    driverClassName: org.postgresql.Driver

  flyway:
    out-of-order: true
    baseline-on-migrate: true
    placeholders:
      defaultMigratorRole: budgettracker

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true